### PR TITLE
Move to Github Actions

### PR DESCRIPTION
**Pull request by nashby**

### CODE REVIEW

**Comment by tashirosota** [comment]
Hi @nashby.
We are many thanks for the enumerize.
I wish you knew [this issue](https://bugs.ruby-lang.org/issues/17509).
I found it and logged for you.

**Comment by nashby** [comment]
hey @tashirosota! Yep, we know it it but thanks anyway!

**Comment by tashirosota** [comment]
Hi @nashby!!
Sorry for this pr is WIP becacse unpassed to ci🙇‍♂️

**Comment by nashby** [comment]
> Hi @nashby!!
> Sorry for this pr is WIP becacse unpassed to ci🙇‍♂️

it's ok, this one is kinda WIP as well anyway :)

**Comment by tashirosota** [comment]
@nashby 
Hi.
I investigated to failed test and listen to ruby developers.
It seems that the behavior of String has changed in the following issues.
https://bugs.ruby-lang.org/issues/10845

**Pull request merged**
