### PR TITLE
Fix issue with ActiveRecord `reload`

### PR DESCRIPTION
**Pull request by RickCSong**
No longer working with ActiveRecord::Store attributes due to changes
from `1b776c`.

### CODE REVIEW

**Comment by nashby** [comment]
Hey @RickCSong! Thank you for the PR! Looks like this one https://github.com/brainspec/enumerize/pull/327/files#diff-7df837b508db8ba4a01d9399b92dba2dR141 and this one https://github.com/brainspec/enumerize/pull/327/files#diff-7df837b508db8ba4a01d9399b92dba2dR149 are the same. I guess you wanted to actually test `reload` method. Could you please fix it? Thanks!

**Comment by RickCSong** [comment]
Thank you for the catch! Updated.

**Comment by RickCSong** [comment]
Let me know if things look good @nashby ! Would love to merge this to fix master :)

**Comment by nashby** [comment]
@RickCSong thanks!

**Comment by RickCSong** [comment]
You're awesome. Thanks @nashby !

**Pull request merged**
